# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Book name')),
                ('author', models.CharField(max_length=120, verbose_name='Author name')),
                ('description', models.TextField(verbose_name='Book description')),
                ('date_added', models.DateField(verbose_name='Date added')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Who added book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text of comment')),
                ('date_added', models.DateTimeField(verbose_name='Date of comment added')),
                ('parent_id', models.IntegerField(default=0, verbose_name='Comment id of parent comment')),
                ('for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Book', verbose_name='Commented book')),
                ('who_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Who added comment')),
            ],
        ),
    ]
